package com.overstar.elasticsearch.dto;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

@Table(name = "`supplier`")
public class Supplier implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.country_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String emailEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.telephone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.telephone_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String telephoneEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.discount_rate
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Double discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.need_eticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean needEticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.pay_max_delay
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer payMaxDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.customer_responsibility
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String customerResponsibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.checkin_tips
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String checkinTips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.create_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.last_update_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.accountant_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String accountantEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.accountant_phone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String accountantPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.currency_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer currencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_period
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer paymentPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_credit
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean paymentCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.mail_booking
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean mailBooking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.cc_emails
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String ccEmails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.confirm_code
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String confirmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.city_ids
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String cityIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.booking_company_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String bookingCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.in_use
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer inUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.mail_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean mailSupplierVoucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.receive_voucher_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String receiveVoucherEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.settlement
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Short settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.pay_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.pay_remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String payRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.pay_account
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Short payAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.pay_account_info
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String payAccountInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.bill_file_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Short billFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.refund_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Short refundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_confirmno
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean supplierConfirmno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.accept_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean acceptSupplierVoucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.change_pay_status
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean changePayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_day
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Short paymentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.disable_payment
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean disablePayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.auto_bill
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean autoBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.show_tel_on_ticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private Boolean showTelOnTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.purchse_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private String purchseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_id
     *
     * @return the value of supplier.supplier_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_id
     *
     * @param supplierId the value for supplier.supplier_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.country_id
     *
     * @return the value of supplier.country_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.country_id
     *
     * @param countryId the value for supplier.country_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_name
     *
     * @return the value of supplier.supplier_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_name
     *
     * @param supplierName the value for supplier.supplier_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email_en
     *
     * @return the value of supplier.email_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getEmailEn() {
        return emailEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email_en
     *
     * @param emailEn the value for supplier.email_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setEmailEn(String emailEn) {
        this.emailEn = emailEn == null ? null : emailEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.telephone
     *
     * @return the value of supplier.telephone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.telephone
     *
     * @param telephone the value for supplier.telephone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.telephone_en
     *
     * @return the value of supplier.telephone_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getTelephoneEn() {
        return telephoneEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.telephone_en
     *
     * @param telephoneEn the value for supplier.telephone_en
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setTelephoneEn(String telephoneEn) {
        this.telephoneEn = telephoneEn == null ? null : telephoneEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.discount_rate
     *
     * @return the value of supplier.discount_rate
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Double getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.discount_rate
     *
     * @param discountRate the value for supplier.discount_rate
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setDiscountRate(Double discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.need_eticket
     *
     * @return the value of supplier.need_eticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getNeedEticket() {
        return needEticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.need_eticket
     *
     * @param needEticket the value for supplier.need_eticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setNeedEticket(Boolean needEticket) {
        this.needEticket = needEticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.pay_max_delay
     *
     * @return the value of supplier.pay_max_delay
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getPayMaxDelay() {
        return payMaxDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.pay_max_delay
     *
     * @param payMaxDelay the value for supplier.pay_max_delay
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPayMaxDelay(Integer payMaxDelay) {
        this.payMaxDelay = payMaxDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.remark
     *
     * @return the value of supplier.remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.remark
     *
     * @param remark the value for supplier.remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.customer_responsibility
     *
     * @return the value of supplier.customer_responsibility
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getCustomerResponsibility() {
        return customerResponsibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.customer_responsibility
     *
     * @param customerResponsibility the value for supplier.customer_responsibility
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCustomerResponsibility(String customerResponsibility) {
        this.customerResponsibility = customerResponsibility == null ? null : customerResponsibility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.checkin_tips
     *
     * @return the value of supplier.checkin_tips
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getCheckinTips() {
        return checkinTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.checkin_tips
     *
     * @param checkinTips the value for supplier.checkin_tips
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCheckinTips(String checkinTips) {
        this.checkinTips = checkinTips == null ? null : checkinTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.create_time
     *
     * @return the value of supplier.create_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.create_time
     *
     * @param createTime the value for supplier.create_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.last_update_time
     *
     * @return the value of supplier.last_update_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.last_update_time
     *
     * @param lastUpdateTime the value for supplier.last_update_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.accountant_email
     *
     * @return the value of supplier.accountant_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getAccountantEmail() {
        return accountantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.accountant_email
     *
     * @param accountantEmail the value for supplier.accountant_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setAccountantEmail(String accountantEmail) {
        this.accountantEmail = accountantEmail == null ? null : accountantEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.accountant_phone
     *
     * @return the value of supplier.accountant_phone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getAccountantPhone() {
        return accountantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.accountant_phone
     *
     * @param accountantPhone the value for supplier.accountant_phone
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setAccountantPhone(String accountantPhone) {
        this.accountantPhone = accountantPhone == null ? null : accountantPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.currency_id
     *
     * @return the value of supplier.currency_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.currency_id
     *
     * @param currencyId the value for supplier.currency_id
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_type
     *
     * @return the value of supplier.payment_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_type
     *
     * @param paymentType the value for supplier.payment_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_period
     *
     * @return the value of supplier.payment_period
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getPaymentPeriod() {
        return paymentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_period
     *
     * @param paymentPeriod the value for supplier.payment_period
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPaymentPeriod(Integer paymentPeriod) {
        this.paymentPeriod = paymentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_time
     *
     * @return the value of supplier.payment_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_time
     *
     * @param paymentTime the value for supplier.payment_time
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime == null ? null : paymentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_credit
     *
     * @return the value of supplier.payment_credit
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getPaymentCredit() {
        return paymentCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_credit
     *
     * @param paymentCredit the value for supplier.payment_credit
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPaymentCredit(Boolean paymentCredit) {
        this.paymentCredit = paymentCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.mail_booking
     *
     * @return the value of supplier.mail_booking
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getMailBooking() {
        return mailBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.mail_booking
     *
     * @param mailBooking the value for supplier.mail_booking
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setMailBooking(Boolean mailBooking) {
        this.mailBooking = mailBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.cc_emails
     *
     * @return the value of supplier.cc_emails
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getCcEmails() {
        return ccEmails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.cc_emails
     *
     * @param ccEmails the value for supplier.cc_emails
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCcEmails(String ccEmails) {
        this.ccEmails = ccEmails == null ? null : ccEmails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.confirm_code
     *
     * @return the value of supplier.confirm_code
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getConfirmCode() {
        return confirmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.confirm_code
     *
     * @param confirmCode the value for supplier.confirm_code
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setConfirmCode(String confirmCode) {
        this.confirmCode = confirmCode == null ? null : confirmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.city_ids
     *
     * @return the value of supplier.city_ids
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getCityIds() {
        return cityIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.city_ids
     *
     * @param cityIds the value for supplier.city_ids
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setCityIds(String cityIds) {
        this.cityIds = cityIds == null ? null : cityIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.booking_company_name
     *
     * @return the value of supplier.booking_company_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getBookingCompanyName() {
        return bookingCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.booking_company_name
     *
     * @param bookingCompanyName the value for supplier.booking_company_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setBookingCompanyName(String bookingCompanyName) {
        this.bookingCompanyName = bookingCompanyName == null ? null : bookingCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.in_use
     *
     * @return the value of supplier.in_use
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.in_use
     *
     * @param inUse the value for supplier.in_use
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setInUse(Integer inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.mail_supplier_voucher
     *
     * @return the value of supplier.mail_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getMailSupplierVoucher() {
        return mailSupplierVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.mail_supplier_voucher
     *
     * @param mailSupplierVoucher the value for supplier.mail_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setMailSupplierVoucher(Boolean mailSupplierVoucher) {
        this.mailSupplierVoucher = mailSupplierVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.receive_voucher_email
     *
     * @return the value of supplier.receive_voucher_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getReceiveVoucherEmail() {
        return receiveVoucherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.receive_voucher_email
     *
     * @param receiveVoucherEmail the value for supplier.receive_voucher_email
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setReceiveVoucherEmail(String receiveVoucherEmail) {
        this.receiveVoucherEmail = receiveVoucherEmail == null ? null : receiveVoucherEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.settlement
     *
     * @return the value of supplier.settlement
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Short getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.settlement
     *
     * @param settlement the value for supplier.settlement
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setSettlement(Short settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.pay_type
     *
     * @return the value of supplier.pay_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.pay_type
     *
     * @param payType the value for supplier.pay_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.pay_remark
     *
     * @return the value of supplier.pay_remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getPayRemark() {
        return payRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.pay_remark
     *
     * @param payRemark the value for supplier.pay_remark
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPayRemark(String payRemark) {
        this.payRemark = payRemark == null ? null : payRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.pay_account
     *
     * @return the value of supplier.pay_account
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Short getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.pay_account
     *
     * @param payAccount the value for supplier.pay_account
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPayAccount(Short payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.pay_account_info
     *
     * @return the value of supplier.pay_account_info
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getPayAccountInfo() {
        return payAccountInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.pay_account_info
     *
     * @param payAccountInfo the value for supplier.pay_account_info
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPayAccountInfo(String payAccountInfo) {
        this.payAccountInfo = payAccountInfo == null ? null : payAccountInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.bill_file_type
     *
     * @return the value of supplier.bill_file_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Short getBillFileType() {
        return billFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.bill_file_type
     *
     * @param billFileType the value for supplier.bill_file_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setBillFileType(Short billFileType) {
        this.billFileType = billFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.refund_type
     *
     * @return the value of supplier.refund_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Short getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.refund_type
     *
     * @param refundType the value for supplier.refund_type
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setRefundType(Short refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_confirmno
     *
     * @return the value of supplier.supplier_confirmno
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getSupplierConfirmno() {
        return supplierConfirmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_confirmno
     *
     * @param supplierConfirmno the value for supplier.supplier_confirmno
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setSupplierConfirmno(Boolean supplierConfirmno) {
        this.supplierConfirmno = supplierConfirmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.accept_supplier_voucher
     *
     * @return the value of supplier.accept_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getAcceptSupplierVoucher() {
        return acceptSupplierVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.accept_supplier_voucher
     *
     * @param acceptSupplierVoucher the value for supplier.accept_supplier_voucher
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setAcceptSupplierVoucher(Boolean acceptSupplierVoucher) {
        this.acceptSupplierVoucher = acceptSupplierVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.change_pay_status
     *
     * @return the value of supplier.change_pay_status
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getChangePayStatus() {
        return changePayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.change_pay_status
     *
     * @param changePayStatus the value for supplier.change_pay_status
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setChangePayStatus(Boolean changePayStatus) {
        this.changePayStatus = changePayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_day
     *
     * @return the value of supplier.payment_day
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Short getPaymentDay() {
        return paymentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_day
     *
     * @param paymentDay the value for supplier.payment_day
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPaymentDay(Short paymentDay) {
        this.paymentDay = paymentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.disable_payment
     *
     * @return the value of supplier.disable_payment
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getDisablePayment() {
        return disablePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.disable_payment
     *
     * @param disablePayment the value for supplier.disable_payment
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setDisablePayment(Boolean disablePayment) {
        this.disablePayment = disablePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.auto_bill
     *
     * @return the value of supplier.auto_bill
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getAutoBill() {
        return autoBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.auto_bill
     *
     * @param autoBill the value for supplier.auto_bill
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setAutoBill(Boolean autoBill) {
        this.autoBill = autoBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.show_tel_on_ticket
     *
     * @return the value of supplier.show_tel_on_ticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public Boolean getShowTelOnTicket() {
        return showTelOnTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.show_tel_on_ticket
     *
     * @param showTelOnTicket the value for supplier.show_tel_on_ticket
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setShowTelOnTicket(Boolean showTelOnTicket) {
        this.showTelOnTicket = showTelOnTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.purchse_name
     *
     * @return the value of supplier.purchse_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public String getPurchseName() {
        return purchseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.purchse_name
     *
     * @param purchseName the value for supplier.purchse_name
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    public void setPurchseName(String purchseName) {
        this.purchseName = purchseName == null ? null : purchseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Thu Mar 28 21:11:43 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierId=").append(supplierId);
        sb.append(", countryId=").append(countryId);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", email=").append(email);
        sb.append(", emailEn=").append(emailEn);
        sb.append(", telephone=").append(telephone);
        sb.append(", telephoneEn=").append(telephoneEn);
        sb.append(", discountRate=").append(discountRate);
        sb.append(", needEticket=").append(needEticket);
        sb.append(", payMaxDelay=").append(payMaxDelay);
        sb.append(", remark=").append(remark);
        sb.append(", customerResponsibility=").append(customerResponsibility);
        sb.append(", checkinTips=").append(checkinTips);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", accountantEmail=").append(accountantEmail);
        sb.append(", accountantPhone=").append(accountantPhone);
        sb.append(", currencyId=").append(currencyId);
        sb.append(", paymentType=").append(paymentType);
        sb.append(", paymentPeriod=").append(paymentPeriod);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", paymentCredit=").append(paymentCredit);
        sb.append(", mailBooking=").append(mailBooking);
        sb.append(", ccEmails=").append(ccEmails);
        sb.append(", confirmCode=").append(confirmCode);
        sb.append(", cityIds=").append(cityIds);
        sb.append(", bookingCompanyName=").append(bookingCompanyName);
        sb.append(", inUse=").append(inUse);
        sb.append(", mailSupplierVoucher=").append(mailSupplierVoucher);
        sb.append(", receiveVoucherEmail=").append(receiveVoucherEmail);
        sb.append(", settlement=").append(settlement);
        sb.append(", payType=").append(payType);
        sb.append(", payRemark=").append(payRemark);
        sb.append(", payAccount=").append(payAccount);
        sb.append(", payAccountInfo=").append(payAccountInfo);
        sb.append(", billFileType=").append(billFileType);
        sb.append(", refundType=").append(refundType);
        sb.append(", supplierConfirmno=").append(supplierConfirmno);
        sb.append(", acceptSupplierVoucher=").append(acceptSupplierVoucher);
        sb.append(", changePayStatus=").append(changePayStatus);
        sb.append(", paymentDay=").append(paymentDay);
        sb.append(", disablePayment=").append(disablePayment);
        sb.append(", autoBill=").append(autoBill);
        sb.append(", showTelOnTicket=").append(showTelOnTicket);
        sb.append(", purchseName=").append(purchseName);
        sb.append("]");
        return sb.toString();
    }
}