
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone : http://eureka1:8080/eureka/
spring:
  application:
    name: ZUUL-GATEWAY

zuul:
  routes:
     api-user:
        path: /api-user/**
        serviceId: USER-CENTER
     api-pro:
        path: /api-pro/**
        serviceId: PRODUCT-SERVICE
     api-es:
        path: /api-es/**
        serviceId: ELASTICSEARCH


