server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8080/eureka/
spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pengfyu?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: ypfect92
    druid:
      initial-size: 3
      max-active: 5
      min-idle: 3


spring:
  datasource:
    product :
      url: jdbc:mysql://127.0.0.1:3306/pengfyu?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: ypfect92

    user:
      url: jdbc:mysql://127.0.0.1:3306/pengfyu?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: ypfect92


mybatis:
    mapper-locations: classpath:/mybatis/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true

pagehelper:
    helper-dialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true

logging:
    file: /logs/goods-server.log
    level:
        com:
            choiceness:
                feigninterface:
                    remote: debug
                goodsserver:
                    dao: debug
    pattern:
        console: '%d{yy-MM-dd HH:mm:ss.SSS}--%p--%t--%c--%m%n'





