server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mysql://dt1.itrip.com/itrip?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: aoliday
    druid:
      initial-size: 3
      max-active: 5
      min-idle: 3
  boot:
    admin:
      client:
        url: http://localhost:9876

mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true


pagehelper:
    helper-dialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
