server:
  port: 9190
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8080/eureka/
spring:
  application:
    name: ELASTICSEARCH

feign:
  hystrix:
    enabled: true

#\u8D85\u65F6\u65F6\u95F4
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#\u8BBE\u7F6E\u4E3A\u6C38\u4E0D\u8D85\u65F6
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false